@ToDoListApi_HostAddress = http://localhost:5000

### Get all tasks
GET {{ToDoListApi_HostAddress}}/api/tasks
Accept: application/json

### Get a task by ID
GET {{ToDoListApi_HostAddress}}/api/tasks/1
Accept: application/json

### Add a new task
POST {{ToDoListApi_HostAddress}}/api/tasks
Content-Type: application/json

{
  "description": "New Task",
  "category": "General",
  "deadline": "2023-12-31",
  "isCompleted": false
}

### Update an existing task
PUT {{ToDoListApi_HostAddress}}/api/tasks/1
Content-Type: application/json

{
  "id": 1,
  "description": "Updated Task",
  "category": "General",
  "deadline": "2023-12-31T23:59:59",
  "isCompleted": true
}

### Delete a task by ID
DELETE {{ToDoListApi_HostAddress}}/api/tasks/1
Accept: application/json